<?php 
return [
	'seo_title'=>'[prov_or_city]关键词1,[prov_or_city]关键词2,[prov_or_city]关键词3',
	'seo_keywords'=>'[prov_or_city]关键词1,[prov_or_city]关键词2,[prov_or_city]关键词3',
	'seo_description'=>'[prov_or_city]某某公司创立于2000年， 经过多年的不懈努力，公司现已经成为一家专业从事IT产品开发、生产和销售的高科技企业。公司成立几年来，一直致力于工控/服务器机箱及各种非标箱体的开发与生产，产品现广泛应用于计算机网络、监控、安防、广电、通讯和仪器设备等多种行业',
	'seo_cwkeyword'=>'厂家,报价,哪家好,批发',
	'site_title'=>'某某机械有限公司',
	'site_url'=>'',
	'site_levelurl'=>'',
	'site_logo'=>'/uploads/image/20170929/fbe0415ab900053aef3846e0077c1ef5.jpg',
	'site_copyright'=>'<p>TEL：010-88888888   MOB:13888888888  EMAIL：66666666@qq.com</p>
<p>本软件已进行版权登记，相关权利受法律保护，著作权信息：中华人民共和国国家版权局 计算机软件著作权登记证书：2018SR118857 </p>
<p>版权所有 © 2022 云优CMS企业网站管理系统（www.yunucms.com）镇江市云优网络科技有限公司 保留所有权利 Powered by <a href=\"http://www.yunucms.com\" target=\"_blank\" style=\"color:#fff\">YUNUCMS v2.3.0</a></p>
<p>提示说明：本网站数据只供云优CMS功能演示使用，相关数据不具真实性，如需要了解云优CMS的相关功能请访问云优CMS官网</p>',
	'site_guide'=>'0',
	'theme_style'=>'default',
	'url_model'=>'1',
	'wap_auto'=>'1',
	'wap_logo'=>'/uploads/image/20170922/20170922163524_57831.jpg',
	'wap_copyright'=>'Powered by YUNUCMS 2.3.0 ©2008-2022 www.yunucms.com',
	'wap_levelurl'=>'1',
	'login_url'=>'yunu.php',
	'seo_bdurl'=>'',
	'seo_area'=>'1',
	'seo_title_area'=>'[prov_or_city]关键词1,[prov_or_city]关键词2,[prov_or_city]关键词3',
	'seo_keywords_area'=>'[prov_or_city]关键词1,[prov_or_city]关键词2,[prov_or_city]关键词3',
	'seo_description_area'=>'[prov_or_city]某某公司创立于2000年， 经过多年的不懈努力，公司现已经成为一家专业从事IT产品开发、生产和销售的高科技企业。公司成立几年来，一直致力于工控/服务器机箱及各种非标箱体的开发与生产，产品现广泛应用于计算机网络、监控、安防、广电、通讯和仪器设备等多种行业',
	'site_protocol'=>'http',
	'site_slide'=>'0',
	'seo_default_area'=>'0',
	'qiniu'=>'0',
	'qiniu_accesskey'=>'',
	'qiniu_secretkey'=>'',
	'qiniu_bucket'=>'',
	'qiniu_domain'=>'',
	'mail_smtp'=>'',
	'mail_smtpport'=>'',
	'mail_username'=>'',
	'mail_password'=>'',
	'mail_setname'=>'',
	'copy_sysname'=>'云优CMS',
	'copy_name'=>'YUNUCMS',
	'copy_url'=>'www.yunucms.com',
	'qiniu_upurl'=>'',
	'seo_hxkeyword'=>'核心关键词1,核心关键词2,核心关键词3',
	'bdqc_appid'=>'',
	'bdqc_apikey'=>'',
	'bdqc_arcretkey'=>'',
	'bdqc_qcnum'=>'0',
	'seo_bdurl_ziurl'=>'',
	'seo_bdxzhurl'=>'',
	'api_wyc'=>'0',
	'wyc_type'=>'1',
	'wyc_percent'=>'0.5',
	'wyc_appid'=>'',
	'wyc_appsecret'=>'',
	'api_bdts'=>'0',
	'api_bdxzh'=>'0',
	'api_bdqc'=>'0',
	'api_xxts'=>'0',
	'seo_bdxzhtype'=>'wap',
	'seo_ctkeyword'=>'词头1,词头2,词头3',
	'api_pmjkhq'=>'0',
	'bdcx_url'=>'',
	'upload_file_size'=>'204800',
	'upload_file_ext'=>'rar,zip,pdf,doc,docx,xls,xlsx,ttf',
	'upload_image_size'=>'700',
	'upload_image_ext'=>'jpg,png,gif,ico',
	'image_watermark'=>'0',
	'image_watermark_pos'=>'9',
	'image_watermark_text'=>'测试文字',
	'image_watermark_text_size'=>'30',
	'image_watermark_text_angle'=>'0',
	'image_watermark_text_color'=>'660707',
	'image_watermark_pic'=>'/uploads/image/20180817/d59dac8f3fa4c93f6f38adeacfdfd629.png',
	'image_watermark_pic_opacity'=>'50',
	'image_watermark_text_font'=>'/uploads/file/20180820/5260f3dc61b3b4e2754771fe29f614e5.ttf',
	'site_ico'=>'/favicon.ico',
	'disablewords_status'=>'0',
	'disablewords_content'=>'最佳，更佳
最具，更具
最爱，更爱
最赚，更赚
最优，更优
最优秀，更优秀
最好，更好
最大，更大
最大程度，更大程度
最高，更高
最高级，更高级
最高端，更高端
最奢侈，更奢侈
最低，更低
最低级，更低级
最底，更底
最便宜，更便宜
史上最低价，史上更低价
最流行，更流行
最受欢迎，更受欢迎
最时尚，更时尚
最聚拢，更聚拢
最符合，更符合
最舒适，更舒适
最先，更先
最先进，更先进
最先进科学，更先进科学
最先进加工工艺，更先进加工工艺
最享受，更享受
国家级，
国家级产品，
全球级，
宇宙级，
世界级，
顶级，
顶尖，
尖端，
顶级工艺，
顶级享受，
高级，
极品，
极佳，
绝佳，
绝对，
终极，
极致，
首个，
首选，
独家，
独家配方，
首发，
全网首发，
全国首发，
首家，
全网首家，
全国首家，
首次，
首款，
全国销量冠军，
国家级产品，
国家，
国家免检，
国家领导人，
填补国内空白，
中国驰名，
驰名商标，
国家品质，
第一，
中国第一，
全网第一，
销量第一，
排名第一，
唯一，
第一品牌，
NO.1，
TOP.1，
独一无二，
全国第一，
一流，
一天，
仅此一天，
老字号，
中国驰名商标，
特供，
专供，
专家推荐，
质量免检，
无需国家质量检测，
免抽检，
国家领导人推荐，
国家机关推荐，
使用人民币图样，
史无前例，
前无古人，
永久，
万能，
祖传，
特效，
无敌，
纯天然，
100%，
高档，
正品，
真皮，
超赚，
精确，
大牌，
金牌，
名牌，
王牌，
领袖品牌，
世界领先，
遥遥领先，
领导者，
缔造者，
创领品牌，
领先上市，
巨星，
著名，
掌门人，
至尊，
巅峰，
奢侈，
优秀，
资深，
领袖，
之王，
王者，
冠军，',
	'api_mediaapikey'=>'',
	'api_media'=>'0',
	'wap_mip'=>'0',
	'admin_list_rows'=>'10',
	'indexhtml'=>'0',
	'autologin'=>'1',
	'api_bdautots'=>'0',
	'api_autologin'=>'0',
	'indexhtml_time'=>'15:14:34',
	'pc_mip'=>'0',
	'pc_auto'=>'0',
	'openarea'=>'0',
	'seo_bdmipurl'=>'',
	'sitemap_auto'=>'0',
	'selsitemap_type'=>'sitemap.htm',
	'sitemap_up_index'=>'daily',
	'sitemap_up_list'=>'daily',
	'sitemap_up_content'=>'daily',
	'sitemap_lev_index'=>'1.0',
	'sitemap_lev_list'=>'0.8',
	'sitemap_lev_content'=>'0.6',
	'sitemap_num'=>'10',
	'sitemap_type'=>'rss.xml,sitemap.xml,sitemap.htm',
	'wap_pre'=>'',
	'tagmainurl'=>'0',
	'sitemap_type_site'=>'1,2,3',
	'sitemap_type_index'=>'1',
	'app_debug'=>'0',
	'sitemap_num_start'=>'0',
	'site_tplfun'=>'0',
];
